name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:


env:
  BUILD_TAG: fail2ban:test
  CONTAINER_NAME: fail2ban

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        iptables:
          - auto
          - nft
          - legacy
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/bake-action@v5
        with:
          targets: image-local
        env:
          DEFAULT_TAG: ${{ env.BUILD_TAG }}
      -
        name: Start
        run: |
          docker compose up -d
        working-directory: test
        env:
          FAIL2BAN_IMAGE: ${{ env.BUILD_TAG }}
          FAIL2BAN_CONTAINER: ${{ env.CONTAINER_NAME }}
          IPTABLES_MODE: ${{ matrix.iptables }}
      -
        name: Check container logs
        uses: crazy-max/.github/.github/actions/container-logs-check@main
        with:
          container_name: ${{ env.CONTAINER_NAME }}
          log_check: "Server ready"
          timeout: 120
      -
        name: Logs
        if: always()
        run: |
          docker compose logs
        working-directory: test
        env:
          FAIL2BAN_IMAGE: ${{ env.BUILD_TAG }}
          FAIL2BAN_CONTAINER: ${{ env.CONTAINER_NAME }}
